# frozen_string_literal: true

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require "cucumber/rails"
require "capybara/rails"
require "capybara/cucumber"
require "selenium-webdriver"

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Capybara Configuration
Capybara.configure do |config|
  # Set the default maximum wait time for asynchronous processes
  config.default_max_wait_time = 5 # seconds

  # Choose the default driver based on whether the scenario is JavaScript-enabled
  config.default_driver = :rack_test
  config.javascript_driver = :selenium_chrome_headless # Use headless Chrome for JS tests

  # Optional: Customize the app host if testing against an external server
  # config.app_host = 'http://localhost:3000'
end

# If you're using RSpec matchers in Cucumber steps
require "capybara/rspec"
World(Capybara::DSL, RSpec::Matchers)

# Include FactoryBot methods if you're using FactoryBot for test data
World(FactoryBot::Syntax::Methods)

# Additional requires and configurations can be placed here
# For example, support for custom matchers, macros, etc.

# NOTE: Hooks have been moved to hooks.rb for better organization
