inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - ".git/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "coverage/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "Gemfile"
    - "config/**/*"
    - "db/schema.rb"
