version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/dev
    tty: true
    container_name: netmgt_web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
