# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.

require "capybara/rspec"

RSpec.configure do |config|
  # rspec-expectations config goes here
  config.expect_with(:rspec) do |expectations|
    # Include chain clauses in custom matcher descriptions
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here
  config.mock_with(:rspec) do |mocks|
    # Prevent mocking or stubbing methods that do not exist on real objects
    mocks.verify_partial_doubles = true
  end

  # Shared context metadata behavior
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Enable `:focus` metadata to run specific tests
  config.filter_run_when_matching(:focus)

  # Persist example statuses to support `--only-failures` and `--next-failure` CLI options
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Disable monkey patching to keep syntax clean and avoid conflicts
  config.disable_monkey_patching!

  # Use documentation formatter for detailed output when running a single file
  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # Profile the 10 slowest examples to identify bottlenecks
  config.profile_examples = 10

  # Run specs in random order to uncover order dependencies
  config.order = :random

  # Seed global randomization to reproduce failures
  Kernel.srand(config.seed)

  # Allow Capybara configuration
  config.before(:suite) do
    Capybara.default_driver = :selenium_chrome
    Capybara.javascript_driver = :selenium_chrome
    Capybara.default_max_wait_time = 5 # Adjust as needed for slow-loading pages
  end

  # Additional helpers for Capybara tests
  config.include(Capybara::DSL, type: :feature)
end
